name: CI

# triger on every push to main branch
on:
  #push:
  #  branches:
  #    - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Switch to helloworld directory
      run: cd HelloWorld
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.403'  #change it with your project requiremnet

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build project
      run: dotnet build --configuration Release --no-restore
    
    - name: Run unit tests
      run: dotnet test --configuration Release --no-build --verbosity normal
    
    - name: Install and configure SonarScanner
      run: |
        dotnet tool install --global dotnet-sonarscanner
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run static code analysis
      run: |
        sonarscanner begin /k:${{ secrets.SONAR_PROJECT_KEY }} /o:${{ secrets.SONAR_ORGANIZATION }} /d:sonar.login=${{ secrets.SONAR_TOKEN }}
        dotnet build --configuration Release
        sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}